"""Increase password_hash length

Revision ID: 349306e0d1e7
Revises: 98c152ce1743
Create Date: 2024-09-11 00:45:17.160346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '349306e0d1e7'
down_revision = '98c152ce1743'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
